# Generated by Django 4.1 on 2022-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
